name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0+fc3142aa9
      - uses: nektro/actions-setup-zigmod

      - name: Build
        run: zig build
        
      - name: Test
        run: zig build test

      - name: Build artifacts
        run: |
          set -e
          declare -a targets=("x86_64-linux" "x86_64-linux-musl" "x86_64-macos" "aarch64-linux" "aarch64-macos")

          for target in "${targets[@]}"; do
            mkdir -p artifacts/$target
            echo "Building target ${target}..."	    
            zig build -Dtarget=${target} -Drelease-safe --prefix artifacts/${target}/
            pushd artifacts/${target}/
            tar cfJ ${target}.tar.xz bin/*
            mv ${target}.tar.xz ../
            popd
          done

      - name: Upload artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: artifacts/*.tar.xz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/x86_64-linux.tar.xz
            artifacts/x86_64-linux-musl.tar.xz
            artifacts/x86_64-macos.tar.xz
            artifacts/aarch64-linux.tar.xz
            artifacts/aarch64-macos.tar.xz
